
import = [
    "~/.config/alacritty/themes/tokyo-night.toml"
]

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[window]
decorations = "None"
padding = { x = 2, y = 1 }

[bell]
duration = 250

[cursor]
vi_mode_style = { shape = "Block", blinking = "On" }

[mouse]
bindings = [
{ mouse = "Right", mods = "None", action = "Paste" },
]

[selection]
save_to_clipboard = true

## FiraCode

[font]
size = 9.0
offset = { x = 0, y = -1 }
glyph_offset = { x = 0, y = -1 }
builtin_box_drawing = false

[font.bold]
family = "FiraCode Nerd Font Mono Med"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono Med"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono Med"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono Med"
style = "Regular"




